### ISSUE TITLE
TokenProg.mint_to generates twice the token program as input

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#86] opened 2023-10-12 16:13 UTC
**Is your enhancement request related to a problem? Please describe.**
Since the [original Ix](https://docs.rs/spl-token/latest/src/spl_token/instruction.rs.html#1080-1107) requires the TokenProg Id as a param, the generator produces the program account input twice.

CIDL:
```
- name: mint
    uses:
      - csl_spl_token.mint_to
```

Generated context:
```
 #[derive(Accounts)]
    pub struct Mint<'info> {
        /// CHECK: fee_payer requires an account info
        #[account(mut, signer)]
        pub fee_payer: AccountInfo<'info>,
        #[account(mut, owner=Pubkey::from_str("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA").unwrap())]
        pub mint: Account<'info, anchor_spl::token::Mint>,
        #[account(mut, owner=Pubkey::from_str("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL").unwrap())]
        pub assoc_token_account: Account<'info, anchor_spl::token::TokenAccount>,

        /// CHECK: owner requires an account info
        #[account(signer)]
        pub owner: AccountInfo<'info>,

        /// CHECK: wallet requires an account info
        pub wallet: AccountInfo<'info>,

        /// CHECK: token_program requires an account info
        pub token_program: AccountInfo<'info>,                        ---------> Same account

        /// CHECK: csl_spl_token_v_0_0_0 requires an account info
        pub csl_spl_token_v_0_0_0: AccountInfo<'info>,                ---------> Same account
    }
```

**Describe the solution you'd like**
To not duplicate accounts

**Comment by JazielGuerrero** [comment] 2023-10-12 16:25
Duplicate of https://github.com/Codigo-io/platform/issues/9

**Closed as not planned by JazielGuerrero** 2023-10-12 16:25 UTC
Labels: Triage, Enhancement
