### ISSUE TITLE
TokenProgram.mint_to `assoc_token_account` param name is inadecuate

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#85] opened 2023-10-12 16:04 UTC
**Is your enhancement request related to a problem? Please describe.**
The spl-token.mint_to ix, when generating code with Codigo, generates a param with the name `assoc_token_account`, referring to the `account_pubkey` of the original Ix. 

This is confusing since the param can be a TokenAccount or an Ata.

**Describe the solution you'd like**
To use the original Ix name, or the Anchor ix warpper's name (`to`), but not to introduce a third name that could potentially generate more confusion.

**Comment by JazielGuerrero** [comment] 2023-12-05 02:58
Related to/Duplicate of: https://github.com/Codigo-io/platform/issues/33

**Closed as not planned by JazielGuerrero** 2023-12-05 02:58 UTC
Labels: Triage, Enhancement
