### ISSUE TITLE
TokenProg.set_authority generates a wrong type/name for the `owned_pubkey` param

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#87] opened 2023-10-12 17:45 UTC
**Describe the bug**
Using `TokenProg.set_authority` generates an account input named `mint` and typed token_prog::Mint for `set_authority` `owned_pubkey` param. 
However, this i[x](https://docs.rs/spl-token/4.0.0/spl_token/instruction/fn.set_authority.html) can be used to update either a mint or a token account, thus both names and type are wrong. 
The wrong type prevents the ix to be used to update the authority of a Token Account.

**To Reproduce**
```
- name: mint
    uses:
      - csl_spl_token.set_authority
```

lib.rs Anchor
```
#[derive(Accounts)]
    pub struct Mint<'info>{
	/// CHECK: fee_payer requires an account info
	#[account(mut, signer)]
	pub fee_payer : AccountInfo<'info>,
    #[account(mut)]
	pub mint: Account<'info,anchor_spl::token::Mint>,    ----> This is incorrect
	/// CHECK: owner requires an account info 
	#[account(signer)]
	pub owner : AccountInfo<'info>,
	/// CHECK: csl_spl_token_v_0_0_0 requires an account info
	pub csl_spl_token_v_0_0_0 : AccountInfo<'info>,}
```

**Expected behavior**
To expect an AccountInfo type, with a proper /// check message, since it is not possible to know if it is a Mint or a TokenAccount

**Platform version:**
 - CLI Version [e.g. v0.1.0]
 - GenService Version v0.8

**Extension (mark with an X the extension):**
 - Solana Native [ ]
 - Solana Anchor [x]

**Comment by JazielGuerrero** [comment] 2023-12-05 02:59
Related to/Duplicate of: https://github.com/Codigo-io/platform/issues/33

**Closed as not planned by JazielGuerrero** 2023-12-05 02:59 UTC
Labels: Triage, Bug
