### ISSUE TITLE
undefined deriveCslSplTokenAccount

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/issues#91] opened 2023-10-18 20:53 UTC
**Describe the bug**
Related to the bug already documented in #26 , when trying to use a csl_token.mint_to in Anchor, the generator infers that I want to pass an ATA, so the client generates a PDA check for the address (Although I'm trying to use a regular TokenAccount).

Nevertheless, the PDA check uses a call to deriveCslSplTokenAccount() that is not defined.
**To Reproduce**
```
- name: mint_to
    uses:
      - csl_spl_token.mint_to
```

![image](https://github.com/Codigo-io/platform/assets/63513231/0761df19-c26f-496a-a1d0-2e2d93671f3a)

**Expected behavior**
To define the fn if needed.

**Platform version:**
 - CLI Version [e.g. v0.1.0]
 - GenService Version v0.8

**Extension (mark with an X the extension):**
 - Solana Native [ ]
 - Solana Anchor [x]

**Comment by JazielGuerrero** [comment] 2023-10-19 13:24
> When trying to use a csl_token.mint_to in Anchor, the generator infers that I want to pass an ATA, so the client generates a PDA check for the address. However, I'm trying to use a regular TokenAccount.

Duplicate of https://github.com/Codigo-io/platform/issues/26

> Nevertheless, if I wanted to use an ata, the PDA check uses a call to deriveCslSplTokenAccount() that is not defined.

This is a bug

Please close this ticket and create a new one to report the bug of undefined `deriveCslSplTokenAccount`, or, modify this ticket to only reflect that bug undefined `deriveCslSplTokenAccount`.

**Comment by julianzamt** [comment] 2023-10-23 13:34
Updated issue to reflect only the `undefined` fn bug yo avoid issue duplication.

**Comment by JazielGuerrero** [comment] 2023-12-05 02:59
Related to/Duplicate of: https://github.com/Codigo-io/platform/issues/33

**Closed as not planned by JazielGuerrero** 2023-12-05 02:59 UTC
Labels: Triage, Bug
